rails_tutorial_link: "https://www.railstutorial.org/"
ruby_rails_link: "https://rubyonrails.org/"
screencast_link: "https://screencasts.railstutorial.org/"
news_link: "https://news.railstutorial.org/"
author_link: "https://www.michaelhartl.com/"
gravatar_link: "https://secure.gravatar.com/"
gravatar_template: "https://secure.gravatar.com/avatar/%{id}?s=%{size}"
gravatar_change_link: "https://gravatar.com/emails"
gravatar_size: 80
avatar_size: 50
logo_size: 200
display_image_size_max: [500, 500]

email_from_default: "noreply@example.com"
development_host: "localhost:3000"

email_from_default: "noreply@example.com"
development_host: "localhost:3000"

languages:
  vi: "Tiếng Việt"
  en: "English"

validation:
  email_regex: !ruby/regexp /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  name_len_max: 50
  email_len_max: 255
  password_len_min: 6
  pwd_expires_long: 2
  content_len_max: 140
  image_type: <%= %w[image/jpeg image/gif image/png] %>
  image_size_max: 5
