rails_tutorial_link: "https://www.railstutorial.org/"
ruby_rails_link: "https://rubyonrails.org/"
screencast_link: "https://screencasts.railstutorial.org/"
news_link: "https://news.railstutorial.org/"
author_link: "https://www.michaelhartl.com/"
languages:
  vi: "Tiếng Việt"
  en: "English"
